export const textos = {
  tituloApp: 'TaskFlow',
  subtituloApp: 'Sua lista de tarefas',
  placeholderNovaTarefa: 'O que você precisa fazer?',
  botaoAdicionar: 'Adicionar',
  listaVazia: 'Nenhuma tarefa por aqui. Adicione a primeira acima.',
  botaoExcluir: 'Excluir tarefa',
  avisoDadosCorrompidos:
    'Não foi possível ler suas tarefas salvas. Uma cópia de segurança foi preservada e a lista foi reiniciada.',
  filtroTodas: 'Todas',
  abaHoje: 'Hoje',
  abaSemana: 'Semana',
  secaoSemData: 'Sem data',
  semanaSemTarefas: 'Sem tarefas',
  botaoLembrete: 'Adicionar lembrete',
  botaoRemoverLembrete: 'Remover lembrete',
  explicacaoNotificacoesTitulo: 'Ativar notificações de lembrete?',
  explicacaoNotificacoesTexto:
    'O TaskFlow avisa quando um lembrete vence, mesmo com a aba em segundo plano. Isso exige permissão do navegador para mostrar notificações.',
  botaoPermitirNotificacoes: 'Permitir notificações',
  botaoAgoraNao: 'Agora não',
  avisoNotificacoesNegadas:
    'As notificações de lembrete estão desativadas. Para ativar, permita notificações para este site nas configurações do navegador.',
  bannerLembretesPerdidosTitulo: 'Lembretes perdidos',
  bannerLembretesPerdidosTexto:
    'Estes lembretes venceram enquanto o app estava fechado:',
  botaoFecharBanner: 'Fechar aviso',
  botaoFalar: 'Criar tarefa por voz',
  botaoPararGravacao: 'Parar gravação',
  botaoCancelarGravacao: 'Cancelar',
  legendaOuvindo: 'Ouvindo…',
  placeholderTranscricao: 'Diga o que você precisa fazer…',
  erroVozNotAllowed: 'Permissão de microfone negada. Ative o microfone nas configurações do navegador.',
  erroVozNoSpeech: 'Não entendi. Nada foi capturado — tente falar novamente.',
  erroVozNetwork: 'Falha de rede durante a gravação. Tente novamente.',
  erroVozAborted: 'A gravação foi interrompida.',
  erroVozOutro: 'Não foi possível usar o microfone agora.',
  botaoTentarNovamente: 'Tentar novamente',
  botaoFechar: 'Fechar',
  badgeEntradaPorVoz: 'Entrada por voz',
  rotuloTituloTarefa: 'Título da tarefa',
  rotuloNota: 'Nota',
  placeholderNota: 'Adicione mais detalhes…',
  rotuloCategoriaCard: 'Categoria',
  rotuloLembreteCard: 'Data e hora',
  avisoDataNoPassado: 'Não entendi a data, confira.',
  botaoDescartar: 'Descartar',
  botaoConfirmarTarefa: 'Confirmar tarefa',
  processandoTranscricao: 'Interpretando com IA…',
  abaCalendario: 'Calendário',
  botaoMesAnterior: 'Mês anterior',
  botaoProximoMes: 'Próximo mês',
  botaoAlternarTema: 'Tema',
  temaSistema: 'Sistema',
  temaClaro: 'Claro',
  temaEscuro: 'Escuro',
  botaoDesfazer: 'Desfazer',
  tarefaConcluida: 'Tarefa concluída',
  tarefaExcluida: 'Tarefa excluída',
  listaVaziaFiltro: 'Nenhuma tarefa nessa categoria.',
  diaSemTarefas: 'Nenhuma tarefa neste dia.',
  avisoNotificacoesNaoAtivadas:
    'Você tem lembretes marcados, mas as notificações ainda não foram ativadas.',
  botaoAtivarNotificacoes: 'Ativar notificações',
  botaoGerenciarCategorias: 'Gerenciar categorias',
  tituloGerenciarCategorias: 'Categorias',
  botaoNovaCategoria: 'Nova categoria',
  botaoEditarCategoria: 'Editar categoria',
  placeholderNomeCategoria: 'Nome da categoria',
  botaoSalvarCategoria: 'Salvar',
  botaoCancelarCategoria: 'Cancelar',
  abaConcluidas: 'Concluídas',
  concluidasListaVazia: 'Nenhuma tarefa concluída ainda.',
  botaoBackup: 'Backup',
  tituloBackup: 'Backup dos dados',
  textoExportar:
    'Baixe um arquivo com todas as suas tarefas e categorias. Guarde-o em algum lugar seguro (e-mail, nuvem, pendrive) para não perder nada se trocar de navegador ou aparelho.',
  botaoExportar: 'Exportar dados',
  textoImportar: 'Selecione um arquivo de backup exportado anteriormente pelo TaskFlow.',
  botaoSelecionarArquivo: 'Selecionar arquivo',
  erroImportarArquivoInvalido:
    'Não foi possível ler este arquivo. Verifique se é um backup válido do TaskFlow.',
  avisoConfirmarImportacaoPrefixo: 'Este arquivo tem',
  avisoConfirmarImportacaoSufixo:
    'Importar vai substituir todos os dados atuais e não pode ser desfeito.',
  botaoConfirmarImportar: 'Substituir dados atuais',
  botaoCancelarImportar: 'Cancelar',
  dadosExportados: 'Backup exportado',
  dadosImportados: 'Dados importados com sucesso',

  placeholderBusca: 'Buscar tarefas…',
  botaoLimparBusca: 'Limpar busca',
  buscaSemResultado: 'Nenhuma tarefa encontrada para essa busca.',
  rotuloTags: 'Tags',
  placeholderNovaTag: 'Adicionar tag e pressionar Enter',
  botaoRemoverTag: 'Remover tag',
  filtrarPorTags: 'Filtrar por tag',

  rotuloRecorrencia: 'Repetir',
  recorrenciaNenhuma: 'Não repetir',
  recorrenciaDiaria: 'Todos os dias',
  recorrenciaSemanal: 'Toda semana',
  recorrenciaMensal: 'Todo mês',
  recorrenciaDiasDaSemana: 'Dias específicos',
  avisoSelecioneUmDia: 'Selecione ao menos um dia da semana.',

  rotuloPrioridade: 'Marcar como importante',
  badgeImportante: 'Importante',

  botaoAdicionarSubtarefa: 'Adicionar item',
  placeholderNovaSubtarefa: 'Novo item da lista…',
  botaoRemoverSubtarefa: 'Remover item',
  botaoExpandirSubtarefas: 'Itens da tarefa',
  botaoEditarSubtarefa: 'Editar item',
  botaoSalvarSubtarefa: 'Salvar item',

  botaoEditarTarefa: 'Editar tarefa',
  tituloEditarTarefa: 'Editar tarefa',
  botaoSalvarEdicao: 'Salvar',
  botaoCancelarEdicao: 'Cancelar',
  tarefaEditada: 'Tarefa atualizada',
} as const;
