export const textos = {
  tituloApp: 'TaskFlow',
  subtituloApp: 'Sua lista de tarefas',
  placeholderNovaTarefa: 'O que você precisa fazer?',
  botaoAdicionar: 'Adicionar',
  listaVazia: 'Nenhuma tarefa por aqui. Adicione a primeira acima.',
  botaoExcluir: 'Excluir tarefa',
  avisoDadosCorrompidos:
    'Não foi possível ler suas tarefas salvas. Uma cópia de segurança foi preservada e a lista foi reiniciada.',
  filtroTodas: 'Todas',
  abaHoje: 'Hoje',
  abaSemana: 'Semana',
  secaoSemData: 'Sem data',
  semanaSemTarefas: 'Sem tarefas',
  botaoLembrete: 'Adicionar lembrete',
  botaoRemoverLembrete: 'Remover lembrete',
  explicacaoNotificacoesTitulo: 'Ativar notificações de lembrete?',
  explicacaoNotificacoesTexto:
    'O TaskFlow avisa quando um lembrete vence, mesmo com a aba em segundo plano. Isso exige permissão do navegador para mostrar notificações.',
  botaoPermitirNotificacoes: 'Permitir notificações',
  botaoAgoraNao: 'Agora não',
  avisoNotificacoesNegadas:
    'As notificações de lembrete estão desativadas. Para ativar, permita notificações para este site nas configurações do navegador.',
  bannerLembretesPerdidosTitulo: 'Lembretes perdidos',
  bannerLembretesPerdidosTexto:
    'Estes lembretes venceram enquanto o app estava fechado:',
  botaoFecharBanner: 'Fechar aviso',
  botaoFalar: 'Criar tarefa por voz',
  botaoPararGravacao: 'Parar gravação',
  botaoCancelarGravacao: 'Cancelar',
  legendaOuvindo: 'Ouvindo…',
  placeholderTranscricao: 'Diga o que você precisa fazer…',
  erroVozNotAllowed: 'Permissão de microfone negada. Ative o microfone nas configurações do navegador.',
  erroVozNoSpeech: 'Não entendi. Nada foi capturado — tente falar novamente.',
  erroVozNetwork: 'Falha de rede durante a gravação. Tente novamente.',
  erroVozAborted: 'A gravação foi interrompida.',
  erroVozOutro: 'Não foi possível usar o microfone agora.',
  botaoTentarNovamente: 'Tentar novamente',
  botaoFechar: 'Fechar',
  badgeEntradaPorVoz: 'Entrada por voz',
  rotuloTituloTarefa: 'Título da tarefa',
  rotuloNota: 'Nota',
  placeholderNota: 'Adicione mais detalhes…',
  rotuloCategoriaCard: 'Categoria',
  rotuloLembreteCard: 'Data e hora',
  avisoDataNoPassado: 'Não entendi a data, confira.',
  botaoDescartar: 'Descartar',
  botaoConfirmarTarefa: 'Confirmar tarefa',
  processandoTranscricao: 'Interpretando com IA…',
} as const;
