/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#faf9ff',
        'surface-dim': '#d8d9e4',
        'surface-bright': '#faf9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3fe',
        'surface-container': '#ecedf8',
        'surface-container-high': '#e6e7f3',
        'surface-container-highest': '#e0e2ed',
        'on-surface': '#181b23',
        'on-surface-variant': '#414754',
        'inverse-surface': '#2d3039',
        'inverse-on-surface': '#eff0fb',
        outline: '#727786',
        'outline-variant': '#c1c6d7',
        primary: '#0058c3',
        'on-primary': '#ffffff',
        'primary-container': '#0070f3',
        'on-primary-container': '#ffffff',
        secondary: '#006c49',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        tertiary: '#722ce3',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#faf9ff',
        'on-background': '#181b23',
        'category-trabalho': '#0070f3',
        'category-casa': '#10b981',
        'category-familia': '#7c3aed',
        'category-compras': '#f59e0b',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        gutter: '16px',
      },
      fontFamily: {
        sans: ['Geist', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '500' }],
        'display-md': ['28px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '500' }],
        'display-md-mobile': ['24px', { lineHeight: '1.2', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
